#!/bin/bash
#TODO: migrate to cherry :^)

function die {
    echo $@ && exit 1
}

vhs validate ./tests/repl/*.tape \
    || die "Syntax error in tests"

for tape in ./tests/repl/*.tape; do
    expected=${tape%.*}.golden.ascii
    result=$(basename ${tape%.*}.ascii)
    vhs < $tape
    diff $expected $result \
        || die "Failed test $tape"
done
