#!/bin/bash
#TODO: migrate to cherry :^)

function die {
    echo $@ && exit 1
}

for filename in ./tests/cli/*.chy; do
    ./zig-out/bin/cherry "$filename" > /dev/null \
        || die "Failed test $filename"
done
