Sleep 500ms
Type "./zig-out/"
Sleep 500ms
Type "bin"
Sleep 500ms
Type "/cherry"
Sleep 500ms
Enter
Sleep 500ms
Type "ls te"
Tab 2
Sleep 500ms
Type "da"
Tab 2
Sleep 500ms
Backspace
Sleep 500ms
Enter
Sleep 500ms
Escape
Type "[A"
Escape
Type "[A"
Escape
Type "[A"
Escape
Type "[A"
Escape
Type "[B"
Escape
Type "[B"
Escape
Type "[B"
Escape
Type "[D"
Escape
Type "[D"
Escape
Type "[D"
Escape
Type "[D"
Escape
Type "[D"
Escape
Type "[D"
Escape
Type "[D"
Escape
Type "[D"
Escape
Type "[D"
Escape
Type "[D"
Escape
Type "[D-l "
Sleep 500ms
Enter
Sleep 500ms
Escape
Type "[A"
Escape
Type "[A"
Escape
Type "[A"
Escape
Type "[A"
Escape
Type "[A"
Escape
Type "[B"
Escape
Type "[B"
Escape
Type "[B"
Escape
Type "[B"
Escape
Type "[B"
Sleep 500ms
Escape
Type "[A"
Sleep 500ms
Enter
Escape
Type "[A"
Escape
Type "[A"
Escape
Type "[A"
Escape
Type "[A"
Escape
Type "[A"
Escape
Type "[A"
Escape
Type "[B"
Escape
Type "[B"
Escape
Type "[B"
Escape
Type "[B"
Escape
Type "[B"
Escape
Type "[A"
Enter
Sleep 500ms
Escape
Type "[A"
Escape
Type "[A"
Escape
Type "[A"
Escape
Type "[A"
Escape
Type "[A"
Escape
Type "[A"
Escape
Type "[B"
Escape
Type "[B"
Escape
Type "[B"
Escape
Type "[B"
Escape
Type "[B"
Sleep 500ms
Ctrl+U
Ctrl+D
Sleep 500ms
Ctrl+D
Sleep 500ms
Ctrl+D

