name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  #schedule:
  #- cron: '0 5 * * *' # run at 5 AM UTC

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0
      - run: |
        # build
        zig build 

        # unit tests
        zig build test

        # code tests
        ./run-all-tests
