name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  #schedule:
  #- cron: '0 5 * * *' # run at 5 AM UTC

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0
      - name: build
        run: zig build
      - name: unit tests
        run: zig build test
      - name: e2e code tests
        run: ./run-all-tests
        #- name: e2e repl tests
      #run: ./run-all-repl-tests
